### PR TITLE
Ensure that tags is made from unique part of path

### LINKED ISSUE #64: Losing / in tag names
I see that this line of the code https://github.com/apigee-127/swagger-converter/blob/master/index.js#L200 removes everything before the last /. 

Is this done as a convenience, or is it the swagger 2.0 spec that the resourcePath can't have / in it? I believe a valid resource could be something like `root/nested` to describe a nested resource.

### PR DESCRIPTION
**Pull request by IvanGoncharov**
~~Fixes #66~~
Fixes #64

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@mohsen1 Can you please review it?

**Comment by mohsen1** [comment]
Fixes #66?

**Comment by IvanGoncharov** [comment]
@mohsen1 my mistake #64

**Comment by IvanGoncharov** [comment]
@mohsen1 I fixed commit message

**Comment by mohsen1** [comment]
I see! LGTM

**Pull request merged**
