### PR TITLE
Don't generate default 200 response if any 2xx response is present

### LINKED ISSUE #78: If not present, a 200 response is added
https://github.com/apigee-127/swagger-converter/blob/007de4d9244e21f51832fa3b7ae9b2148b06034f/index.js#L567-L582

1. This should probably be a `default` response
2. It should only be added if no responses are present

Refs https://github.com/LucyBot-Inc/api-spec-converter/issues/136

### PR DESCRIPTION
**Pull request by joepeding**
Currently, a default `200` response is added to every operation (and subsequently overwritten if the source specification also has a `200` defined for that operation).
This is fine for operations that have no response defined, because it keeps the spec valid. But it's bad for operations that do not return a `200`, but rather a `201` or a `204`. There currently is no way to prevent these incorrect `200`s from being added.

This PR turns the generation of these default responses into an option.  A new parameter `generateDefaultResponses` is added that takes 1 of 3 values:
 - To maintain backwards compatibility, the default for this parameter is `always`, which keeps the current behaviour.  
 - With `fallback` this parameter makes the converter behave in (what I think is) the correct fashion: only adding the default response if no other response is defined for the operation. For a new major release, I'd suggest making this the default.
 - It also accepts the value `never`, which completely turns off generation of the default response. While this will produce invalid specs if the source spec has an operation without a response, it might be useful to have a validator show you where the errors are rather than have the converter silently fix them.

I use this converter through https://github.com/LucyBot-Inc/api-spec-converter which already has a passthrough option that allows the use of this new parameter without further changes to api-spec-converter

Fixes #78

### CODE REVIEW

**Comment by joepeding** [comment]
@googlebot I signed it!

**Comment by joepeding** [comment]
@IvanGoncharov: You seem responsible for the last commits to this repository (even though that's a long time ago), can I ask you for a review on this PR?

**Comment by IvanGoncharov** [comment]
@joepeding Thanks for the PR 👍 
I don't like to add options unless absolutely necessary.
So I suggest just checking if a response has any `2xx` response and skipping default `200` in this case.
Also, it's not a breaking change just a bug fix so we don't need `always`.

> It also accepts the value never, which completely turns off generation of the default response. While this will produce invalid specs if the source spec has an operation without a response, it might be useful to have a validator show you where the errors are rather than have the converter silently fix them.

This converter has many places that do similar fixes or trying to guess what the spec author meant so I don't think we should add individual flags but instead add one `noFix` boolean flag that disables all attempts to fix stuff.
Anyway, it should be a separate PR.

**Comment by IvanGoncharov** [comment]
@joepeding Also to be extra careful I will release it as `2.0.0` and do other cleanup tasks (update deps, drop Bower, etc.).

**Comment by IvanGoncharov** [comment]
@joepeding Can you please rebase since I removed `browser` files?

**Comment by IvanGoncharov** [comment]
@joepeding Can you please add a test?

**Comment by joepeding** [comment]
Thanks for the quick review and feedback, this makes it a lot cleaner!

I will add a test, but I'm not sure I'll have time for that today/this week.

**Comment by IvanGoncharov** [comment]
@joepeding No problem. I will add them.

**Comment by joepeding** [comment]
@IvanGoncharov I added a test.

**Comment by IvanGoncharov** [comment]
@googlebot I consent.

**Comment by IvanGoncharov** [comment]
@joepeding Released as `2.0.0` 🎉

**Pull request merged**
