### PR TITLE
Prepare 1.1.0 release

### PR DESCRIPTION
**Pull request by IvanGoncharov**
@mohsen1 I prepared everything for `1.1.0` release
Please publish it on NPM

### CODE REVIEW

**Comment by mohsen1** [comment]
Cool! TravisCI is setup to release tagged commits. https://github.com/apigee-127/swagger-converter/commit/13cdc0ec0a013a7297ee5194b2034e9c02a60011

Make sure you're updating both package.json and bower.json when bumping versions. I recommend using `mversion` package from npm.

**Comment by IvanGoncharov** [comment]
@mohsen1 Thanks for tip about `mversion`.

**Comment by mohsen1** [comment]
No problem. I don't see you updated bower.json though

**Comment by IvanGoncharov** [comment]
@mohsen1 I did both in c4c9954a809443e75442fefb4569219621a1c4fd. I thought it make more sense to make it as direct commit.

**Comment by mohsen1** [comment]
:+1:

**Comment by mohsen1** [comment]
Could you please add the release notes 
https://github.com/apigee-127/swagger-converter/releases/tag/v1.1.0

**Comment by IvanGoncharov** [comment]
@mohsen1 Done. Can you check please?

**Comment by mohsen1** [comment]
Looks good!

**Pull request merged**
