### PR TITLE
Switch to 'sway' for validation

### PR DESCRIPTION
**Pull request by IvanGoncharov**

### CODE REVIEW

**Comment by mohsen1** [comment]
Why there are failures?

**Comment by IvanGoncharov** [comment]
I use not only errors but also warnings. And it uncovered some problems. I will try to fix it next couple of days.

**Comment by IvanGoncharov** [comment]
I fix most of warnings, they were related to unconverted `authorizations` object.
I commented check of warnings and will fix it in the next PR.
@mohsen1 Can you review it?

**Comment by mohsen1** [comment]
Hey @IvanGoncharov I am traveling right now so I might not be able to release this shortly but I will release it as soon as I can. 

Thanks!

**Pull request merged**
