### PR TITLE
Add 'listApiDeclarations' function.

### PR DESCRIPTION
**Pull request by IvanGoncharov**
@mohsen1 Can you please review?
If general idea is ok, I will work on tests and docs.

### CODE REVIEW

**Comment by mohsen1** [comment]
Are you trying to guess it or is it always accurate? This can make the API simpler and I like it. My only concern is, if it's working for all 1.2 specs

**Comment by IvanGoncharov** [comment]
@mohsen1 I used `swagger-js` converter as reference and also tested it on 300+ `1.2` specs.
I didn't tested it on `1.1` or `1.0` but according to `swagger-js` it should be only one special rule for `1.0`.

**Comment by mohsen1** [comment]
Works for me then

**Comment by IvanGoncharov** [comment]
@mohsen1 I made all required changes, can you take a look?

**Comment by mohsen1** [comment]
LGTM!

**Comment by IvanGoncharov** [comment]
This is big change, so I think it need NPM release.
It's new API function, so it should be `1.1.0`.
I don't have keys for NPM so it should you.
P.S. If you want you can setup this: https://docs.travis-ci.com/user/deployment/npm/

**Pull request merged**
