### PR TITLE
Change API

### PR DESCRIPTION
**Pull request by IvanGoncharov**

### CODE REVIEW

**Comment by mohsen1** [comment]
I believe this changes the browser API also. Do you want to update that in this PR also?

**Comment by IvanGoncharov** [comment]
@mohsen1 Sorry, I don't understand. Do you speaking about browser examples inside README?

**Comment by mohsen1** [comment]
Yes, no worries. I'll release it tomorrow and update the README. 

Is there anything left from version 1.0.0 work?

**Comment by IvanGoncharov** [comment]
@mohsen1 No.

**Comment by IvanGoncharov** [comment]
@mohsen1 On second thought, update `uglify-js` to remove [insecure banner](https://david-dm.org/apigee-127/swagger-converter#info=devDependencies).

**Comment by IvanGoncharov** [comment]
@mohsen1 And change `1.2` to `1.x` in description of repo.

**Pull request merged**
