### PR TITLE
Allow override of the collectionFormat

### PR DESCRIPTION
**Pull request by MikkelTAndersen**
…o 2.0 spec.

Usage:

var swaggerConverter = require('swagger-converter');
// this makes the swagger ui add collections as multiple query params.
swaggerConverter.options.collectionFormat = 'multi';

### CODE REVIEW

**Comment by MikkelTAndersen** [comment]
I left it as csv since the swagger spec says its default to csv, this allows you to override it when you call the convert.

**Comment by IvanGoncharov** [comment]
@MikkelTAndersen 
On technical side: `buildTypeProperties` convert both parameters and JSON Schemas. Swagger allow `collectionFormat` only in parameters. This can be fix by changing `allowRef` into `isJsonSchema` and only if it `false` then add `collectionFormat`. I also prefer not to bloat Swagger with fields which have default values, so adding `collectionFormat` make sense only if it not `csv`.

More important question, why `csv` not working for you? Is it common problem or just your particular case? To answer this, can you describe how 1.2 spec was generated? Which framework or maybe written by hand?

**Comment by MikkelTAndersen** [comment]
So we use wildfly/jboss, and it supports multi instead of csv, so I
defaulted to csv to be backwards compatible but in my script I put in the
'multi' value, since that is how our Jaxrs/jackson/wildfly understands it.
So the spec file in 1.2 does not have that information available so this
option provides a meaningful default and a way to set it in general.... I
will work on setting it up only for parameters.  It must be a common issue
as we have multiple applications running with the same issue.

We use the swagger-jaxrs-docklet to generate the 1.2 spec.
Thanks for your time.

**Comment by IvanGoncharov** [comment]
Also please check this code https://github.com/apigee-127/swagger-converter/blob/master/index.js#L594

**Comment by IvanGoncharov** [comment]
@MikkelTAndersen One more thing, global option isn't good for this use case.
You need to set different values based on which Swagger documents you convertion right now.
In my particular use case I convert  hundreds of Swagger specs from different sources and do it asynchronously. 

Please make options as 3rd argument of `convert` function then save it inside `Converter` object.
So inside `buildTypeProperties` you will get it like that: `this.options.collectionFormat`

**Comment by IvanGoncharov** [comment]
@MikkelTAndersen Don't forget to update README and add some test. Without test there is a chance that option will be broken in future.
In README please mention about `Jaxrs/jackson/wildfly` behaviour, it will save a lot of time for other developers.

**Comment by IvanGoncharov** [comment]
Also please remove `when upgrade from old format to 2.0 spec` part from commit message.
It don't provide any additional info since this entire lib is for `upgrade from old format to 2.0 spec`.

**Comment by MikkelTAndersen** [comment]
... so I updated to code, but the comment 'This can be fix by changing allowRef into isJsonSchema and only if it false then add collectionFormat' I dont understand, do you want me to refactor the name allowRef to isJsonSchema ? 


I will work on an extra test case.

**Comment by IvanGoncharov** [comment]
@MikkelTAndersen It easier for me to implement this feature. I write more comments than actual code to discuss. I will create PR today and ask you to participate in review. Will it work for you?

**Comment by MikkelTAndersen** [comment]
Thank you so much ! that is very much appreciated :)

**Comment by IvanGoncharov** [comment]
@MikkelTAndersen I added #65, please review it

**Pull request closed without merging**
